### ISSUE TITLE
Completion Provider fails at getting any CST nodes

### ISSUE THREAD

**Issue by Lotes** [eclipse-langium/langium#1076]
Langium version: 1.1.0

I prepared a [Gist](https://gist.github.com/Lotes/fbaf002ef0f5e451c06065a9168d49f8) for you.

I added a test in there that tries to complete
```sql
SELECT m.mana|gerId FROM managers m JOIN employees e ON m.managerId=e.id WHERE m.employeeId = 123;
```
where `|` is the position of the cursor.

I expected to get some CST node that gets forwarded to `completionFor(...)` but in fact the method gets not entered.

**Comment by msujew** [comment]
@Lotes this is due to the completion parser being stuck in an ambiguity at the `SELECT m.` part. It's not capable of differentiating between 

```
{infer TableRelatedColumnExpression} variableName=[SourceItem:Identifier] '.' columnName=[ColumnNameSource:Identifier]
``` 
and 
```
{infer ColumnNameExpression} columnName=[ColumnNameSource:Identifier]
```

 which exists within the same alternative.

In order to fix this, the alternatives for `TableRelatedColumnExpression`, `FunctionCall` and `ColumnNameExpression` should be refactored into a single expression that looks like:

```
{infer ReferenceExpression}reference=GlobalReference (functionCall='(' args+=... ')')?
```

Then perform validation on top of it to ensure that the referenced element is valid in the used context.

One could argue that the heuristic shouldn't break, but I don't think it's possible to improve on this with the tools we have. The grammar should be refactored to be more permissive and less ambiguous. I'll close this.
