### ISSUE TITLE
NextFeature.property calculation is broken with a datatype rule

### ISSUE THREAD

**Issue by cdietrich** [eclipse-langium/langium#1203]
Adapt the hello world grammar terminals to

```
ID returns string: ID1 | ID2;
terminal ID1: /[_a-zA-Z][\w_-]*/;
terminal ID2: /`[^`]*`/;
```

upon completion on

```
person |
```
the value of `next.property` is `undefined`.
i would expect it to be `name`

**Comment by msujew** [comment]
Interesting finding. I can reproduce the issue and created a proposed fix in [here](https://github.com/eclipse-langium/langium/tree/msujew/fix-next-element-compute). I'll continue working on that tomorrow, since I might have found another potential issues related to the `new` flag of the computed value that I want to fix in there as well.
