### ISSUE TITLE
enhance the default keywords autocomplete

### ISSUE THREAD

**Issue by Yokozuna59** [eclipse-langium/langium#1227]
Hi there,

Currently, the default keyword autocompletion doesn't autocomplete the keyword; it inserts the whole word again.

![image](https://github.com/eclipse-langium/langium/assets/87622592/c047e37a-70c9-4991-8df3-b68fb26f4001)

![image](https://github.com/eclipse-langium/langium/assets/87622592/7cf60d76-af1f-4080-b70f-0602dd937010)

**Comment by msujew** [comment]
I assume that's another consequence of the whitespace sensitive language. Can you reproduce this behavior in the playground?

**Comment by Yokozuna59** [comment]
> Can you reproduce this behavior in the online playground using the hello world language?

No, I can't reproduce this behavior in the online playground using the hello world language or the Info language. So it's all because of the inserted newline from Lexer.

Is there an expected date for the next release? I want to try the `EOF` to see if it would resolve all these errors.
I [saw that](https://github.com/eclipse-langium/langium/discussions/564?sort=new#discussioncomment-7252139) it would be this week or early next week. But I'm not sure exactly when.

**Comment by msujew** [comment]
Unfortunately, I didn't have time to prepare a new release last week, and everyone capable (including me) is at EclipseCon during the coming week. I'll probably have time to publish a `next` release on Sunday though.

Note that I'm not entirely sure the EOF token actually fixes this, since it will just be there in place of the newline token. The completion algorithm should probably skip the token, but that isn't implemented yet.
