### ISSUE TITLE
Completely optional parser rules should be marked as errors

### ISSUE THREAD

**Issue by msujew** [eclipse-langium/langium#1400]
Related to https://github.com/eclipse-langium/langium/issues/1398

A parser rule that potentially consumes no input from the text is not valid, as the parser can potentially not attempt to create it:

```ts
Persons:
    ((elements+=ID) (elements+=ID)*)?;
```

This leads to unexpected behavior, and generally serves no purpose. We have a similar validation for terminals already, and should have one for parser rules as well.

**Comment by spoenemann** [comment]
My two cents:
- A rule marked as entry should be excluded from this validation: you usually want an empty file to be valid.
- I'd already raise an error if a rule can _potentially_ not consume any input, which means you don't have to care about guard conditions. If you encounter an alternative, check whether any of the alternatives is potentially empty.
- When calling other rules, I'd assume that they do consume input, so that counts as being non-empty.
- I would also count actions like `{MyType}` as being non-empty. Actually we could offer a code action as quick fix that adds an action to enforce the rule to be valid despite consuming no tokens.

**Comment by bjthehun** [comment]
>     * I would also count actions like `{MyType}` as being non-empty. Actually we could offer a code action as quick fix that adds an action to enforce the rule to be valid despite consuming no tokens.

So to clarify, this grammar would be valid, right?

```
grammar HelloWorld

interface Empty {};

entry Model:
    Emptyness;
// Action that consumes nothing
Emptyness: {Empty};

hidden terminal WS: /\s+/;

hidden terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
hidden terminal SL_COMMENT: /\/\/[^\n\r]*/;
```

Also, what about fragments? Should optionality be checked for them, too?

**Comment by spoenemann** [comment]
> So to clarify, this grammar would be valid, right?

It would be helpful if that works, but I'm not sure whether it's problematic for the parser.

> Also, what about fragments? Should optionality be checked for them, too?

No, a fragment should be allowed to consume no tokens. When calling a fragment rule, treat its content as if it was part of the calling rule.

**Comment by bjthehun** [comment]
OK. I've changed the validation to reflect these cases, and to fix false-positive errors with alternative groups.
