### ISSUE TITLE
Proposal missing from the content assist

### ISSUE THREAD

**Issue by ydaveluy** [eclipse-langium/langium#1677]
Hey !

I probably found a minor issue in the content assist in case of multiple keyword alternatives. It seems that if the previous token is of a keyword kind, this keyword is not proposed by the content assist.

Langium version: 3.1
Package name: Langium

## Steps To Reproduce

1. Open this  [playground](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD4AWAlrrogHawAuiIEJlYysGAygFywD0AOgGcA1DwDc%2BOgyYtYASQAi3HgG0A%2BmAC0ALwCCGgFoBdPgHcAVGMLEyFapMbNWAWQAyqgMIB5J04CiAOQAVJT5%2BM2VBPnZDMwB%2BPjNQy1JyKlp6Bxl2Ny8fAODeUNDlAD0%2BSj4QGMt8KhoQAE9YX0p6hs58WC7YAApO7oGAcgEaAFdbGkHYEfG64QBeBVgAH36BrsG6MABjInoprd36BYU12ABKM3xRIA&content=FAZwLgrgJgpgdmABAIWGGBDAxgCxgJ0QEFgg) 
2. Ctrl+space on line 4

## The current behavior
The content assist propose to create a new 'student' but not an other 'teacher'. After a 'student', the content assist propose to create a 'teacher' but not an other 'student'.

## The expected behavior
The content assist should propose a 'student' and a 'teacher' in all cases.

**Comment by msujew** [comment]
Hm, interesting. It's also pretty interest that this can be pretty easily fixed by using a small refactoring of the grammar. See [here](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD4AWAlrrogHawAuiIEJlYysGAygFywD0AOgGcA1DwDc%2BOgyYtYASQAi3HgG0A%2BmAC0ALwCCGgFoBdPgHcAVGMLEyFapMbNWAWQAyqgMIB5J04CiAOQAVJT5%2BM2VBPnZDMwB%2BPjNQy1JyKlp6Bxl2Ny8fAODeUNDlAD0%2BSj4QGMt8KhoQAE9YX0p6hs58WC7YAAoSOghhAF4e9hoAV1saAB9AxDAAYyJ6AEoVs3xxfDHJuu4AcgEJqf3YZghEIYUtucXlkAO6O-pT88vroA&content=M4FwrgJgpgdiAEBBAsAKBFAhgYwBZQCd4AhNIA).

**Comment by ydaveluy** [comment]
Yes, in your refactoring, 'student' and 'teacher' are on different AstNodes, and it works properly.

In my case, I think the issue comes from `DefaultCompletionProvider.findFeaturesAt`, which does not return the previous feature, but I don't fully understand how this function works.

**Comment by msujew** [comment]
Yeah, I'm not saying that this isn't a bug - but there are at least in theory ways to circumvent this. I've added this to https://github.com/eclipse-langium/langium/issues/1678.

**Comment by ydaveluy** [comment]
Thanks for the workaround.

I continued investigating this issue and I noticed that we enter in this branch for the missing feature: https://github.com/eclipse-langium/langium/blob/b2a6fe9684434117eb6a344fc2721e3c26d989bf/packages/langium/src/lsp/completion/follow-element-computation.ts#L131

It means that the previous feature is added in the visited Set somewhere before processing the Group.
