### ISSUE TITLE
"Connection.onInitialized()" crashes the language server

### ISSUE THREAD

**Issue by Drakae** [eclipse-langium/langium#1774]
Langium version: 3.3.0
Package name:

When calling the "onInitialized()" function on the language server connection to the client, the language server stops working. Even if I use yeoman to create a sample Langium project, I get this issue if I add the following lines in the main.ts file of the language server:
```
connection.onInitialized(() => {
    console.log('Connection initialized');
});
```

## Steps To Reproduce

1. Use or create a new langium project (with yeoman)
2. In src/language/main.ts add the following lines at the end of the file:
```
connection.onInitialized(() => {
    console.log('Connection initialized');
});
```

Link to code example: [https://github.com/Drakae/langiumBug](url)

## The current behavior
The language server does not respond anymore in terms of parsing, scoping, etc.

## The expected behavior
The language server should still respond with parsing, scoping, etc.

**Comment by msujew** [comment]
Hey @Drakae,

I guess this is intended behavior? By calling `connection.onInitialized` you're overriding our `onInitialized` call:

https://github.com/eclipse-langium/langium/blob/e004619e1428cdf44899771aed7cde1b98512271/packages/langium/src/lsp/language-server.ts#L259-L261

This prevents our language services from starting up correctly. Since `onInitialized` isn't an event mechanism, but just sets a listener, you're supposed to use our [`LanguageServer#onInitialized`](https://eclipse-langium.github.io/langium/interfaces/langium_lsp.LanguageServer.html#onInitialized) event instead.

**Comment by Drakae** [comment]
Thank your very much, that resolves my issue. I didn't know that :)
